#  Copyright (c) 2017-2018 Thomas Heller
#  Copyright (c) 2015 Martin Stumpf
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

test_filter: &test_filter
    filters:
      branches:
        ignore: gh-pages
      tags:
        only: /.*/

version: 2

jobs:
  test_step_1:
    docker:
      - image: stellargroup/build_env:ubuntu
    working_directory: /hpx
    steps:
      - run:
          name: Testing CircleCI tag building
          command: |
              echo CIRCLE_TAG=${CIRCLE_TAG}
              echo CIRCLE_BRANCH=${CIRCLE_BRANCH}
    <<: *test_filter
  test_step_2:
    docker:
      - image: stellargroup/build_env:ubuntu
    working_directory: /hpx
    steps:
      - run:
          name: Testing CircleCI tag building
          command: |
              echo CIRCLE_TAG=${CIRCLE_TAG}
              echo CIRCLE_BRANCH=${CIRCLE_BRANCH}
    <<: *test_filter

workflows:
  version: 2
  build-and-test:
    jobs:
      - test_step_1
      - test_step_2
          requires:
            - test_step_1
